### ISSUE TITLE
请问：在一个测试类中需要使用多个页面元素应该怎么操作？

### ISSUE THREAD

**Issue by Chen2358** [BarryYBL/UIAutoDemo#1]
比如，登录（loginPage）后需要做下单（orderPage）操作？

**Comment by BarryYBL** [comment]
如果多页都在当前标签页进行，用元素控制就可；如果多页建立跳转在新标签页那么就定位到新标签页就好了

登录可以是全局，你也可以写到一个case里

**Comment by Chen2358** [comment]
已解决，感谢回复
