### ISSUE TITLE
请问：我在run.py中使用测试用例所在的目录，在运行第二个用例的时候会断开链接，提示“对方积极拒绝......”

### ISSUE THREAD

**Issue by Chen2358** [BarryYBL/UIAutoDemo#2]

**Comment by Chen2358** [comment]
![Uploading image.png…]()

**Comment by Chen2358** [comment]
![image](https://user-images.githubusercontent.com/29376276/96527474-b8de7f00-12b2-11eb-8203-32c2c06afb58.png)

**Comment by Chen2358** [comment]
用例说明：test06 Traceback (most recent call last):   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connection.py", line 160, in _new_conn     (self._dns_host, self.port), self.timeout, **extra_kw   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection     raise err   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection     sock.connect(sa) ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen     chunked=chunked,   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request     conn.request(method, url, **httplib_request_kw)   File "D:\install\miniconda3\Lib\http\client.py", line 1252, in request     self._send_request(method, url, body, headers, encode_chunked)   File "D:\install\miniconda3\Lib\http\client.py", line 1298, in _send_request     self.endheaders(body, encode_chunked=encode_chunked)   File "D:\install\miniconda3\Lib\http\client.py", line 1247, in endheaders     self._send_output(message_body, encode_chunked=encode_chunked)   File "D:\install\miniconda3\Lib\http\client.py", line 1026, in _send_output     self.send(msg)   File "D:\install\miniconda3\Lib\http\client.py", line 966, in send     self.connect()   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connection.py", line 187, in connect     conn = self._new_conn()   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connection.py", line 172, in _new_conn     self, "Failed to establish a new connection: %s" % e urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C94F45C208>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "D:\Tester\workspace\sogaaautotest\SogaaUIAutoTest\test_case\test02_work_standard.py", line 26, in setUpClass     cls().start()   File "D:\Tester\workspace\sogaaautotest\SogaaUIAutoTest\test_case\test02_work_standard.py", line 18, in start     self.dr.get(StandardPage.url)   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\poium\page_objects.py", line 69, in get     self.driver.get(root_uri + uri)   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get     self.execute(Command.GET, {'url': url})   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute     response = self.command_executor.execute(driver_command, params)   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute     return self._request(command_info[0], url, body=data)   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request     resp = self._conn.request(method, url, body=body, headers=headers)   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\request.py", line 80, in request     method, url, fields=fields, headers=headers, **urlopen_kw   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\request.py", line 171, in request_encode_body     return self.urlopen(method, url, **extra_kw)   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen     response = conn.urlopen(method, u.request_uri, **kw)   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connectionpool.py", line 767, in urlopen     **response_kw   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connectionpool.py", line 767, in urlopen     **response_kw   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connectionpool.py", line 767, in urlopen     **response_kw   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\connectionpool.py", line 727, in urlopen     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]   File "D:\Tester\Scripts\UIAutoTest\UIAutoEnv\lib\site-packages\urllib3\util\retry.py", line 439, in increment     raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49389): Max retries exceeded with url: /session/93fb3b194cf036ef233c2371e39aecdb/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C94F45C208>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
--

**Comment by BarryYBL** [comment]
![image](https://user-images.githubusercontent.com/46100874/96527564-f7743980-12b2-11eb-8e03-fae796755c74.png)

把tearDownClass方法删除即可，因为你在第一个case类主动关闭了浏览器，导致启动器关闭；所以你的第二个case类就没有了启动器以至于你的第二个case出现所上描述

**Comment by Chen2358** [comment]
已解决，感谢回复。
