### ISSUE TITLE
请问下，想问下在执行完一个用例，再执行下一个用例时的步骤是什么？

### ISSUE THREAD

**Issue by Chen2358** [BarryYBL/UIAutoDemo#3]
执行完第一个用例后，我观察到页面会重新有个刷新动作。具体想问下，执行第二个用例前页面是会返回到哪里？比如，第一个是登录，第二个是其他操作，第三个是退出，在执行完第二个用例后，不是直接执行第三个用例，而是先转到登录后首页后再执行第三个退出用例。

**Comment by BarryYBL** [comment]
通常自动化用例设计，就是执行完一个case，浏览器信息就需要重新载入，以确保每个case的用例执行设计的真实性；但每执行完一个case，也只是会在当前页刷新

**Comment by Chen2358** [comment]
明白了，感谢
