### ISSUE TITLE
本机的浏览器版本是87，但是驱动官网下载的版本是88，这样就无法驱动了

### ISSUE THREAD

**Issue by debugerliu** [BarryYBL/UIAutoDemo#4]
建议能不能根据本机的浏览器版本搜索和下载驱动

**Comment by BarryYBL** [comment]
由于Chromedriver版本发行比Chrome要块，你可以从Chrome官网下载Bata版本；从本地暂时没有想到很好的方法去实现

**Comment by debugerliu** [comment]
# coding=utf-8 import time from selenium import webdriver driver = webdriver.Chrome() driver.maximize_window() driver.implicitly_wait(6) driver.get("http://www.baidu.com/") time.sleep(1) print(driver.capabilities['version']) # 打印浏览器version的值 driver.quit() 使用这个方法，配合无头浏览器，神不知鬼不觉的处理好

**Comment by BarryYBL** [comment]
这个方法是，必须要代用Chromedriver，但是如果你本地浏览器与驱动版本不对其实还是无法掉起成功的；况且就他会告诉你版本不对应；但是启动器已经结束停止了；

**Comment by debugerliu** [comment]
对对对，我没想到，是我无知了，

**Comment by BarryYBL** [comment]
有一个方法我可以解决我只检查调用最新版本的问题，我改为可选择版本就可以了；后面可能会更新

**Comment by debugerliu** [comment]
我现在就是写死了把他，写成了我现在浏览器的版本号

**Comment by BarryYBL** [comment]
嗯嗯，感谢您的支持
